server:
  port: 6662
spring:
  application:
    name: crawler-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/loqvliuliang/crawler-config/     # 配置git仓库的地址
          search-paths:                            # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号
          password:                                             # git仓库的密码
